//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT_MASTER()
        {
            this.SALES_ORDER_DETAILS = new HashSet<SALES_ORDER_DETAILS>();
        }
    
        public string PRODUCTNO { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PROFITPERC { get; set; }
        public string UNITMEASURE { get; set; }
        public decimal QTYONHAND { get; set; }
        public decimal REORDERLVL { get; set; }
        public decimal SELLPRICE { get; set; }
        public decimal COSTPRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_ORDER_DETAILS> SALES_ORDER_DETAILS { get; set; }
    }
}
