//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_ORDER_DETAILS
    {
        public string ORDERNO { get; set; }
        public string PRODUCTNO { get; set; }
        public Nullable<decimal> QTYORDERED { get; set; }
        public Nullable<decimal> QTYDISP { get; set; }
        public Nullable<decimal> PRODUCTRATE { get; set; }
    
        public virtual PRODUCT_MASTER PRODUCT_MASTER { get; set; }
        public virtual SALES_ORDER SALES_ORDER { get; set; }
    }
}
