//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALES_ORDER()
        {
            this.SALES_ORDER_DETAILS = new HashSet<SALES_ORDER_DETAILS>();
        }
    
        public string ORDERNO { get; set; }
        public string CLIENTNO { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public string DELYADDR { get; set; }
        public string SALESMANNO { get; set; }
        public string DELYTYPE { get; set; }
        public string BILLENDYN { get; set; }
        public Nullable<System.DateTime> DELYDATE { get; set; }
        public string ORDERSTATUS { get; set; }
    
        public virtual CLIENT_MASTER CLIENT_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES_ORDER_DETAILS> SALES_ORDER_DETAILS { get; set; }
        public virtual SALESMAN_MASTER SALESMAN_MASTER { get; set; }
    }
}
