create table CLIENT_MASTER(
   CLIENTNO varchar(6) primary key ,
   NAME  varchar(20) not null,
   ADDRESS1 VARCHAR(30),
   ADDRESS2 VARCHAR(30),
   CITY VARCHAR(15),
   PINCODE numeric(8) ,
   STATE VARCHAR(15),
   BALDUE numeric(10,2)
);

create table PRODUCT_MASTER(
       PRODUCTNO VARCHAR(6) PRIMARY KEY,
	   DESCRIPTION VARCHAR(15) NOT NULL,
	   PROFITPERC NUMERIC(4,2) NOT NULL,
	   UNITMEASURE VARCHAR(10) NOT NULL,
	   QTYONHAND NUMERIC(8) not null,
	   REORDERLVL NUMERIC(8) NOT NULL,
	   SELLPRICE NUMERIC(8,2) NOT NULL  CHECK(SELLPRICE != 0),
	   COSTPRICE NUMERIC(8,2) NOT NULL check (COSTPRICE !=0 ));



CREATE TABLE SALESMAN_MASTER(
    SALESMANNO VARCHAR(6) PRIMARY KEY ,
	SALESMANNAME VARCHAR(20) NOT NULL,
	ADDRESS1 VARCHAR(30) NOT NULL,
	ADDRESS2 VARCHAR(30),
	CITY VARCHAR(20),
	PINCODE NUMERIC(8),
	STATE VARCHAR(20) ,
	SALAMT NUMERIC(8,2) NOT NULL check (SALAMT != 0),
	TGTTOGET NUMERIC(6,2) NOT NULL,
	YTDSALES NUMERIC(6,2) NOT NULL,
	REMARKS VARCHAR(60)
);
CREATE TABLE SALES_ORDER(
    ORDERNO VARCHAR(6) PRIMARY KEY ,
	CLIENTNO VARCHAR(6) FOREIGN KEY REFERENCES CLIENT_MASTER,
	ORDERDATE DATE,
	DELYADDR VARCHAR(25),
	SALESMANNO VARCHAR(6) FOREIGN KEY REFERENCES SALESMAN_MASTER,
	DELYTYPE CHAR(1) CHECK (DELYTYPE ='P' OR DELYTYPE = 'S'),
	BILLENDYN CHAR(1) CHECK (BILLENDYN ='Y' OR BILLENDYN ='N'),
	DELYDATE DATE,
	ORDERSTATUS VARCHAR(10) CHECK(ORDERSTATUS = 'Process' or ORDERSTATUS ='Fulfilled' or ORDERSTATUS = 'Backorder' or ORDERSTATUS = 'Cancelled')
);

CREATE TABLE SALES_ORDER_DETAILS(
    ORDERNO VARCHAR(6) FOREIGN KEY REFERENCES SALES_ORDER,
	PRODUCTNO VARCHAR(6) FOREIGN KEY REFERENCES PRODUCT_MASTER,
	QTYORDERED NUMERIC(8),
	QTYDISP NUMERIC(8),
	PRODUCTRATE NUMERIC(10,2),
	primary KEY (ORDERNO,PRODUCTNO)

);


INSERT INTO Client_Master (ClientNo, Name, City, PinCode, State, BalDue) VALUES ('C00001', 'Ivan Bayross', 'Mumbai', 400054, 'Maharashtra', 15000); 
INSERT INTO Product_Master VALUES ('P00001', 'T-Shirts', 5, 'Piece', 200, 50, 350, 250);
INSERT INTO Salesman_Master VALUES ('S00001', 'Aman', 'A/14', 'Worli', 'Mumbai', 400002, 'Maharashtra', 3000, 100, 50, 'Good'); 
INSERT INTO Sales_Order (OrderNo, OrderDate, ClientNo, DelyType, BILLENDYN, SalesmanNo, DelyDate, OrderStatus)
VALUES('O19001', '12-june-02', 'C00001', '', 'N', 'S00001', '20-july-02', 'In Process');
INSERT INTO Sales_Order_Details (OrderNo, ProductNo, QtyOrdered, QtyDisp, ProductRate) VALUES('O19001', 'P00001', 4, 4, 525);

SELECT * FROM SALES_ORDER


INSERT INTO Sales_Order (ORDERNO,ORDERDATE, CLIENTNO,DELYTYPE, BILLENDYN, SALESMANNO, DELYDATE, ORDERSTATUS)
VALUES('O19001', '12-june-02', 'C00001', 'S', 'N', 'S00001', '20-july-02', 'Process');


/* 1ST */

SELECT NAME FROM CLIENT_MASTER;

/*2ND */

SELECT NAME FROM CLIENT_MASTER WHERE CITY = 'Mumbai';

/*3RD*/

SELECT DESCRIPTION FROM PRODUCT_MASTER WHERE SELLPRICE > 2000 AND SELLPRICE < 5000;

/*4TH*/
SELECT NAME , CITY,STATE FROM CLIENT_MASTER WHERE STATE != 'Maharashtra';

/* Display all the information of client_no C0001 and C0002. */

select * from CLIENT_MASTER where CLIENTNO = 'C0001' OR CLIENTNO = 'C0002';


DELETE FROM CLIENT_MASTER WHERE CLIENTNO='C0005';

SELECT * FROM CLIENT_MASTER WHERE CITY Like '_a%';


SELECT COUNT(*) as number FROM PRODUCT_MASTER where SELLPRICE >= 1500; 

ALTER TABLE CLIENT_MASTER ADD Phone_no VARCHAR(20);

ALTER TABLE CLIENT_MASTER ALTER COLUMN NAME VARCHAR(60);




ALTER TABLE CLIENT_MASTER drop COLUMN pincode;

ALTER TABLE CLIENT_MASTER ADD PRIMARY KEY(CLIENTNO);

ALTER TABLE CLIENT_MASTER ADD  PHONE_NO NUMERIC(10) ;

select * from CLIENT_MASTER;